services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: excel
    ports:
      - "5432:5432"
  api:
    image: exceltable
    build:
      context: .
      dockerfile: ExcelTable/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CUSTOMCONNSTR_DefaultConnection: "Host=db;Port=5432;Database=excel;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - db