services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: excel
    ports:
      - "5432:5432"
  api:
    image: exceltable
    build:
      context: .
      dockerfile: ExcelTable/Dockerfile
    depends_on:
      - db