services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: excel
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d excel" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  api:
    image: exceltable
    restart: always
    build:
      context: .
      dockerfile: ExcelTable/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CUSTOMCONNSTR_DefaultConnection: "Host=db;Port=5432;Database=excel;Username=postgres;Password=postgres"
      AllowedOrigins: "http://localhost:8080,http://localhost:3000"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  web:
    image: exceltableweb
    restart: always
    build:
      context: .
      dockerfile: excel-table-web/Dockerfile
    environment:
      BACKEND_API_URL: "http://api:8080"
    ports:
      - "3000:3000"
    depends_on:
      - api