name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define Image Tag
        run: |
          echo "IMAGE_TAG=ghcr.io/${{ github.actor }}/exceltable:${{ github.sha }}" >> $GITHUB_ENV

      #- name: Build and Tag Image
      #  run: |
      #    docker build -f ExcelTable/Dockerfile -t ${{ env.IMAGE_TAG }} .

      #- name: Push Image to GitHub Container Registry
      #  run: |
      #    docker push ${{ env.IMAGE_TAG }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          file: ExcelTable/Dockerfile
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Deploy the app to Digital Ocean
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ env.IMAGE_TAG }}
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          
