name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t your-image-name:tag ExcelTable
          docker push ghcr.io/${{ github.repository }}:$IMAGE_TAG
