name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Tag Image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.actor }}/exceltable:${{ github.sha }}
          docker build -f ExcelTable/Dockerfile -t $IMAGE_TAG .
          docker push $IMAGE_TAG
